### ISSUE TITLE
Doesn't destroy and rebuild properly

### ISSUE THREAD

**Issue by BennyCarlsson** [jechav/tiny-slider-react#13]
On unmount the slider doesn't get destroyed proberly.

I have a component using the slider. 
It get images as props.
When the image props changes the component rerender. The slider tries to destroy() and rebuild() however slider state is not properly destroyed and the slider ends up with old and new images.

Will try to extract the component to show of a minimum example.

**Comment by BennyCarlsson** [comment]
Created minimum project to reproduce the bug
https://codesandbox.io/s/tiny-slider-bug-qji0w

**Comment by ferblacklion** [comment]
Try 

> On unmount the slider doesn't get destroyed proberly.
> 
> I have a component using the slider.
> It get images as props.
> When the image props changes the component rerender. The slider tries to destroy() and rebuild() however slider state is not properly destroyed and the slider ends up with old and new images.
> 
> Will try to extract the component to show of a minimum example.

Hello try to use this package is a fork 
https://github.com/ferblacklion/tiny-slider-react

**Comment by jechav** [comment]
fixed v0.5.2

**Comment by EgorKluch** [comment]
v0.5.3 - issue reproduced.

**Comment by care4pet** [comment]
Yep, still the same.
