### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by Aryan-mor** [jechav/tiny-slider-react#15]
Error on using tiny slider react in NextJs.

> [ error ] ./node_modules/ventura-slider/dist/tiny-slider.css
> Global CSS cannot be imported from within node_modules.
> 
> Read more: https://err.sh/next.js/css-npm
> 
> Location: node_modules\tiny-slider-react\build\Carousel.js

![Untitled](https://user-images.githubusercontent.com/22844436/76460594-87840380-63f3-11ea-8110-e6a83a9127f3.jpg)

**Comment by jechav** [comment]
This should be addressed directly to the author of the library, since this is only a wrapper.
https://github.com/ganlanyuan/tiny-slider

**Comment by nicholasio** [comment]
@jechav I don't think this is an issue with tiny-slider. The original implementation doesn't load the css by default it explicitly delegates to the consumer to load the CSS. The issue with your wrapper is that it makes an assumption about how every app is loading CSS.

This issue should be resolved by simple removing the line that loads the CSS, ship the compiled css to npm, then updating instructions to let users now that they should load the CSS themselves.
