### ISSUE TITLE
Lazyload lazyLoadEager not supported?

### ISSUE THREAD

**Issue by laraduarte** [jechav/tiny-slider-react#17]
The lazyload feature only loads the current item.
Is it possible to load 3 images? 

The attachment shows what happens when the user slides and the image is still not loaded.

Thanks 

![Screenshot (421)](https://user-images.githubusercontent.com/1926934/82304768-aa630300-99b4-11ea-9b62-6c2bb71845b9.png)

Lara

**Comment by jechav** [comment]
updated tiny-slider v2.9.2

**Comment by laraduarte** [comment]
Same issue! was not resolved on version 2.9.2

**Comment by jechav** [comment]
I remove an old logic regarding the lazyload, but i think is not related.
anyway the there is an example with your settings in the demo:
https://tiny-slider-react-tests.netlify.app/
