### ISSUE TITLE
Nav container's buttons and next / prev button type

### ISSUE THREAD

**Issue by oleksandr-omelchenko-ks** [jechav/tiny-slider-react#22]
Currently all of these buttons does not have `type="button"` so if `<TinySlider />` is injected inside form any click on them triggers form submit. It would be nice to add this button type.

Somehow connected question: how do I create custom `navContainer` if this key can only accept HTMLElement and not JSX?

**Comment by jechav** [comment]
This an internal tiny-slider issue, you should report it here https://github.com/ganlanyuan/tiny-slider.

**Comment by oleksandr-omelchenko-ks** [comment]
@jechav I can see that on [demo page](http://ganlanyuan.github.io/tiny-slider/demo/) navigation buttons has attribute `type="button"`, check please.
