### ISSUE TITLE
Window undefined error in serverside rendering

### ISSUE THREAD

**Issue by creativehubspace** [jechav/tiny-slider-react#25]
When testing this module in a GatsbyJs project, I get the following error message **"window" is not available during server side rendering.** .
`WebpackError: ReferenceError: window is not defined`. The error is in the file **tiny-slider/src/helpers/raf.js** where the window object is defined as `var win = window;`

**Comment by nicknish** [comment]
Yup this seems to be an issue with [tiny-slider](https://github.com/ganlanyuan/tiny-slider#tiny-slider-2).

> Warning: tiny-slider works with static content and it works in the browser only. If the HTML is loaded dynamically, make sure to call tns() after its loading.

To get around this, I stubbed TinySlider when in SSR then dynamically imported in when out of SSR:

```jsx
// BREAKS SSR
// import TinySlider from 'tiny-slider-react'

let TinySlider = ({ children }) => children

if (typeof window !== 'undefined') {
	TinySlider = require('tiny-slider-react')
} 
```
