### ISSUE TITLE
val1.map is not a function

### ISSUE THREAD

**Issue by UladzKha** [jechav/tiny-slider-react#28]
I added this libraby into my project, configured, but when i try to use state i get this error
![image](https://user-images.githubusercontent.com/1148497/93349198-7cdd7780-f837-11ea-8afa-07f765af977e.png)
please solve it i do need it.

**Comment by care4pet** [comment]
> I added this libraby into my project, configured, but when i try to use state i get this error
> ![image](https://user-images.githubusercontent.com/1148497/93349198-7cdd7780-f837-11ea-8afa-07f765af977e.png)
> please solve it i do need it.

Did you managed to resolve it?
