### ISSUE TITLE
How to change slides properly? 

### ISSUE THREAD

**Issue by Maclay74** [jechav/tiny-slider-react#30]
I have slider with products and filters.
When filters change, I want to get new products from backend and show new slides.

I think it's quite trivial use case, but seems like it's impossible to change slides.

Is there a way to handle it?

**Comment by Dobby89** [comment]
I would also like to know how to do this @jechav .

How do you programatically change slides?

**Comment by jechav** [comment]
Hi in the readme there is an example using ref.
`onGoTo = dir => this.ts.slider.goTo(dir)`
