### ISSUE TITLE
Having issue with SSR anti-pattern platform(Next.js)

### ISSUE THREAD

**Issue by curavcy** [jechav/tiny-slider-react#36]
Can we update the styling for support the Next.js ? 
> Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Read more: https://err.sh/next.js/css-global
![image](https://user-images.githubusercontent.com/54394008/117745448-594cb000-b1bf-11eb-93a9-d77d511f1012.png)

**Comment by vousys** [comment]
Hi @curavcy, could you fix it?

**Comment by jechav** [comment]
https://github.com/jechav/tiny-slider-react/pull/41 with this PR was fixed.
