### ISSUE TITLE
Not work "autoWidth"

### ISSUE THREAD

**Issue by FromSi** [jechav/tiny-slider-react#5]
Hello, jechav!
I did not use plugin "tiny-slider" but I understand something about how it should work in practice.
**I use your "tiny-slider-react" and could not get the proper effect of "autoWidth".**

Does "autoWidth" work in version 0.4.0?

**Comment by d3haynes** [comment]
Setting autoWidth to true will add the class tns-autowidth to the slider which sets it to display: inline-block, so it appears to working. Are you not seeing that?

**Comment by FromSi** [comment]
I can not check. I don't use ReactJS anymore :( sry

**Comment by jechav** [comment]
updated tiny-slider v2.9.2
